# Costapine Linux - SDDM PAM configuration overrides/security settings
# This file can be used to set environment variables or configuration options for SDDM PAM module.

# Default session services to allow
auth        required    pam_env.so
auth        required    pam_unix.so nullok_secure
account     required    pam_unix.so
password    required    pam_unix.so shadow md5
session     required    pam_unix.so
session     optional    pam_elogind.so
